### ISSUE TITLE
After adding enchantment to armor

### ISSUE THREAD

**Issue by SpecialistNinja** [room17/ExplosiveEnvoys#1]
17.02 23:15:32 [Server] Server thread/DEBUG #0 ExplosiveEnvoys_dev-1.phar/src/ExplosiveEnvoys/ExplosiveEnvoys(135): ExplosiveEnvoys\ExplosiveEnvoys::parseItem(string 303, 1, 0, 1)
17.02 23:15:32 [Server] Server thread/DEBUG #1 ExplosiveEnvoys_dev-1.phar/src/ExplosiveEnvoys/envoy/EnvoyManager(88): ExplosiveEnvoys\ExplosiveEnvoys::parseItems(array Array())
17.02 23:15:32 [Server] Server thread/DEBUG #2 ExplosiveEnvoys_dev-1.phar/src/ExplosiveEnvoys/envoy/EnvoyManager(122): ExplosiveEnvoys\envoy\EnvoyManager->spawnEnvoy(pocketmine\level\Position object)
17.02 23:15:32 [Server] Server thread/DEBUG #3 ExplosiveEnvoys_dev-1.phar/src/ExplosiveEnvoys/envoy/EnvoyTask(24): ExplosiveEnvoys\envoy\EnvoyManager->update()
17.02 23:15:32 [Server] Server thread/DEBUG #4 src/pocketmine/scheduler/TaskHandler(160): ExplosiveEnvoys\envoy\EnvoyTask->onRun(integer 421)
17.02 23:15:32 [Server] Server thread/DEBUG #5 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 421)
17.02 23:15:32 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2543): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 421)
17.02 23:15:32 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2285): pocketmine\Server->tick()
17.02 23:15:32 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2158): pocketmine\Server->tickProcessor()
17.02 23:15:32 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1744): pocketmine\Server->start()
17.02 23:15:32 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(385): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
17.02 23:15:32 [Server] Server thread/DEBUG #11 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
17.02 23:15:33 [Server] Server thread/CRITICAL Could not execute task ExplosiveEnvoys\envoy\EnvoyTask: Call to undefined method pocketmine\item\enchantment\ProtectionEnchantment::setLevel()
17.02 23:15:33 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\item\enchantment\ProtectionEnchantment::setLevel()" (EXCEPTION) in "ExplosiveEnvoys_dev-1.phar/src/ExplosiveEnvoys/ExplosiveEnvoys" at line 117

**Comment by dresnite** [comment]
Thanks for your report @SpecialistNinja, it'll be fixed soon!
