### ISSUE TITLE
No Chest

### ISSUE THREAD

**Issue by SpecialistNinja** [room17/ExplosiveEnvoys#5]
Every envoy that spawn show up with no chest and no one can get the loot
![image](https://user-images.githubusercontent.com/33918083/37233216-2ba46750-23a7-11e8-834a-46e96acde8bd.png)

**Comment by SpecialistNinja** [comment]
@specialistninja This only happen when Envoy spawn below ground, the one that spawn above sky is fixed

**Comment by dresnite** [comment]
Thanks for reporting this issue, @SpecialistNinja. — I already knew it, I'll be fixing it and updating this plugin asap!
